### PR TITLE
Project setup

### PR DESCRIPTION
**Pull request by Alusp**
## I implemented the following in this PR:

- [ ] Create a new Rails app called 'hello-rails-react'.
- [ ] Follow Gitflow
- [ ] Add linters Configurations
- [ ] Use the commend rails new -j webpack my_new_rails_app as described in the previous lesson's tutorial.
- [ ] Verified that the jsbundling-rails gem is added to my Gemfile.
- [ ] Install needed node dependencies.
- [ ] Create a babel.config.js in the root folder of my project.
- [ ] Update webpack.config.js to include the babel loader.
- [ ] Make sure that my project has a Postgres database set up.
- [ ] Create a table for storing my messages and create 5 different greetings.
- [ ] Create an API endpoint that selects a random greeting from my table.
- [ ] Create a static view that will be the root of your app.
- [ ] Create the App component with react-router and render it in my static view.
- [ ] Create the Greeting component that will display a greeting. Set it up as a route in my App component.
- [ ] Create a store, an action, and a reducer that will connect to my API endpoint to get the random greeting.
- [ ] Display the random greeting in your Greeting component.

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @Alusp 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has node modules committed to Git and you don't have the future features section in your readme

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Alusp** [comment]
Oh alright it totally skipped my mind, thanks for the review @prolajumokeoni

**Review by rustam-tolipov — APPROVED** [review]
Hi @Alusp, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Developer-512px-10

## Highlights
1. No Linters errors 💯
2. All requirements are complete 💯

## Optional suggestions

You are free to remove this line from your readme:

> NOTE: we recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository). You can also use [any other license](https://choosealicense.com/licenses/) if you wish.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Alusp** [comment]
Thanks very much for the review @Rustamxon7

**Pull request merged**
